### ISSUE TITLE
Question: Why use chart.yaml to include original helm chart

### ISSUE THREAD

**Issue by east4ming** [khuedoan/homelab#181]
I see that there is a Chart.yaml under the directory of each app. Some Chart.yaml files are very simple, just adding an extra layer on top of the official Helm Chart.

Chart.yaml like this:

```yaml
apiVersion: v2
name: volsync
version: 0.0.0
dependencies:
  - name: volsync
    version: 0.12.0
    repository: https://backube.github.io/helm-charts
```

I read the official documentation of argocd, and there are no similar best practices. Could you please explain why this approach is taken? What are the benefits of doing this compared to the official examples (directly including the entire helm chart or using [multi-source](https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/)?

Thanks
