### ISSUE TITLE
dhcpd.conf template does not render

### ISSUE THREAD

**Issue by ahgraber** [khuedoan/homelab#48]
I'm working through your netboot solution, and I have an interesting issue where dhcpd.conf.j2 does not render properly (no variables are substituted).  All of the other templates work just fine, and the variables used in dhcpd.conf.j2 are available if I run a debug step:

```yaml
# all variables are present with correct values
- debug:
    var: '{{item}}'
  with_items:
    - ansible_default_ipv4.address
    - ansible_default_ipv4.broadcast
    - ansible_default_ipv4.gateway
    - ansible_default_ipv4.netmask
    - ansible_default_ipv4.network

# no substitution occurs
- name: Render DHCP config
  template:
    src: dhcpd.conf.j2
    dest: "{{ role_path }}/files/dhcp/dhcpd.conf"
    mode: 0644

# substitution occurs correctly
- name: Render GRUB config
  template:
    src: grub.cfg.j2
    dest: "{{ role_path }}/files/data/boot/grub/grub.cfg"
    mode: 0644
```

Do you have any thoughts?
