### ISSUE TITLE
Switching chart provider

### ISSUE THREAD

**Issue by gitbute** [khuedoan/homelab#94]
Hi there

As the k8s-at-home charts are marked as deprecated / archived and wont get updated regularly,
i propose we switch to something that still is maintained for the default app-stack.

I mainly played around with a combination of [https://github.com/truecharts](https://github.com/truecharts) and linuxserver.io images where i didnt found a suitable image. I mostly had good results and more up to date apps.

If you would like me to get some of the apps ported over, i will gladly make some pull requests.

Best regards
gitbute

**Comment by gitbute** [comment]
So, Truecharts decided to not support native helm deployments anymore, only on their Truenas SCALE solution.
It looks like we to search another common chart provider for these apps.

**Comment by khuedoan** [comment]
Worst case scenario we can maintain our own charts, as I did with the `cloudflared` chart (though it's a little out of date 😅).

**Comment by dotdiego** [comment]
k8s-at-home can be replaced with a library chart by one of k8s-at-home charts maintainer.
See more here : https://bjw-s.github.io/helm-charts/docs/app-template/introduction.html

I could not make it work with ArgoCD + Helm though. I used Kustomized Helm to make it work.

See below example for Jellyfin.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    version: 1.3.0
    releaseName: &releaseName jellyfin
    namespace: &releaseNamespace jellyfin
    valuesFile: values.yaml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
```
